### PR TITLE
Implement remaining To-Dos

### PR DESCRIPTION
**Pull request by bjoluc**
This resumes work from #1:

- [x] The predefined sequence should just start with one color/tone and after correct reproduction by the subject, increase by +1 color/tone.
- [x] Reaction times should be recorded (for the whole sequence only)

So far, I didn't remove per-button response times in case they prove useful one day.

### CODE REVIEW

**Comment by bjoluc** [comment]
> Very much related to (2) and (3) I think, would it be possible to get the output file as a .csv as I usually work in R? Would that mean that we could obtain one row per (sub-)sequence?

Without further ado, csv would look like this:

response | sequence | mode | rt
-- | -- | -- | --
[{"button":0,"delta_time":328},{"button":1,"delta_time":255},{"button":0,"delta_time":234},{"button":0,"delta_time":198}] | [0,1,0,1] | audiovisual | 1015
... | ... | ... | ...

Button presses are nested and still JSON. Would this still be easier to work with for you?

**Comment by SchluneggerDaniel** [comment]
> 

That’s much easier to work with! 👍

**Comment by bjoluc** [comment]
I added a `makeSequencesAdaptive()` function to `src/data/sequences.ts`. To achieve To-Do (2), you can use it like this:

```ts
export const practiceSequences = makeSequencesAdaptive([
  { mode: 'audiovisual', sequence: [0, 1, 0, 1] },
  { mode: 'visual', sequence: [0, 1, 1, 0] },
  { mode: 'audiovisual', sequence: [0, 1, 2, 0, 1, 2] },
  { mode: 'visual', sequence: [0, 3, 2, 1, 3, 2, 1, 0] },
]);

```

EDIT: I forgot to mention that it turns
```ts
{ mode: 'audiovisual', sequence: [0, 1, 0, 1] },
```
into
```ts
{ mode: 'audiovisual', sequence: [0] },
{ mode: 'audiovisual', sequence: [0, 1] },
{ mode: 'audiovisual', sequence: [0, 1, 0] },
{ mode: 'audiovisual', sequence: [0, 1, 0, 1] },
```
so there are simply more trials with partial sequences.

**Comment by bjoluc** [comment]
This should be it then. Is there anything else you would like me to help with?

**Comment by SchluneggerDaniel** [comment]
Perfect! I think that is everything. Thank you very much!

**Pull request merged**
